
const actionType = {

    CHANGEUSERNAME : 'CHANGEUSERNAME',
    CHANGEEMAIL : 'CHANGEEMAIL',
    FETCK_OK : "FETCK_OK",
    FETCH_FAILED : "FETCH_FAILED",
    FETCHING : "FETCHING",
    GETTING : "GETTING",
    GET_OK : "GET_OK",
    GET_FAILED : "GET_FAILED",
    GET_LIST : "GET_LIST",
    GET_LIST_ERROR : "GET_LIST_ERROR",
    GET_CURRENCY_NAME : "GET_CURRENCY_NAME",
    BROWSE_DATA : "BROWSE_DATA",
    BROWSE_OK : "BROWSE_OK",
    BROWSE_ERROR : "BROWSE_ERROR",
    THIS_LANGUAGE : "THIS_LANGUAGE",
    THIS_BTC : "THIS_BTC",
    THIS_BTC_UP_DOWN : "THIS_BTC_UP_DOWN"
}

export default actionType ;